### ISSUE TITLE
Organizers and Events pages don't load

### ISSUE THREAD

**Issue by Splaktar** [GDG-Missoula/gdg-missoula.github.com#1]
Just need to change HUB URLs from `http` to `https`.

You may also want to check out the [instructions here](https://github.com/gdg-x/boomerang/wiki/Host-your-chapter-website-on-GitHub-in-15-minutes/) for a guide to forking this and making updates a bit easier.

**Comment by exavatar** [comment]
Update the protocol, and events and organizers are showing again.  Thanks Michael!

**Comment by Splaktar** [comment]
:+1:
